### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hellc** [eoshubio/eoshub-ios#5]
Please, provide software license info into your code repo. 
Is it Apache 2.0?

**Comment by eoshubio** [comment]
We are using GPL 3.0. Please check in the develop branch.
https://github.com/eoshubio/eoshub-ios/blob/develop/LICENSE

Thank you for your interest.

**Comment by hellc** [comment]
You are welcome

**Comment by hellc** [comment]
@eoshubio also check out your license inside iOS app. Last time I saw it, it was Apache 2.0.
